/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class func_ndk__NdkUtil */

#ifndef _Included_func_ndk__NdkUtil
#define _Included_func_ndk__NdkUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     func_ndk__NdkUtil
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_func_ndk_1_NdkUtil_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
